Feature/friends/#4
TeamDeli/Deli-Front pull request #23
Opened 2021-08-05 16:05 UTC by lizuAg

![image](https://user-images.githubusercontent.com/68546023/128383184-21768dbc-6ad4-46c7-a251-34824bf599f2.png)

2021-08-05 16:20 UTC, kiiiyeon requested changes
굿굿 너무잘했어요~!❤
라우터 만들어서 PR다시 해주시면 감사하겠습니다❤❤❤
천천히 만들어도 괜찮아요~!

문구는... 어떻게 수정하면 좋을지 내일 함께 상의해봐요~!

2021-08-05 16:20 UTC, kiiiyeon commented on src/components/friends/UserInfo.js
> +  console.log("userInfo");
콘솔 빼고 올려주세요❤

2021-08-05 16:20 UTC, kiiiyeon commented on src/components/friends/Friends.js
> +        {friendsList && friendsList.map((friend, i) => <p id={i}>{friend}</p>)}
이거 넘 잘했다!!
근데 wishlist에서는 id={index}이던데 이걸로 통일하는건 어떨까요?!

2021-08-05 16:20 UTC, kiiiyeon commented on src/components/friends/WishList.js
> +          })}
구현 빡셌겠는데 ㅋㅋㅋㅋ
코드멋져요 굿👍

2021-08-05 16:39 UTC, lizuAg commented on src/components/friends/Friends.js
> +        {friendsList && friendsList.map((friend, i) => <p id={i}>{friend}</p>)}
넵 id가 아니라 key값이었어요.. ㅋㅋㅋㅋㅋㅋ 통일해서 수정완료 !!

2021-08-06 01:33 UTC, KilTae approved these changes
수고하셨습니다~!! 리알못이라.. 코드를 보면서., 배워가요.,

2021-08-06 03:57 UTC, bsorinnn requested changes
우와 너무 잘했는데요!! 코드에서 많이 배우고 갑니다👏 라우터만 추가하면 되겠어요☺️

2021-08-06 09:58 UTC, kyungminlee-12 approved these changes
다시보는 빙수 반갑ㅋㅋㅋ 수고하셨습니다!!

2021-08-07 15:58 UTC, kiiiyeon approved these changes
너무잘했어요오오오!!!!!
어푸루브 받아 마땅!! 어푸루브 땅땅!!!
쏘굿❤❤❤❤

2021-08-07 15:58 UTC, kiiiyeon commented on src/components/friends/Friends.js
> +        친구 찾기
이 부분이 원래 제 뷰에서 친구 글자 누르면 주은이 페이지로 이동하게 하는 거였는데 
아직 주은이 페이지가 나온 상태가 아니어서 그냥 링크를 저렇게 연결해놓은거였거든요?!
주은이는 친구 찾기가 그냥 글씨면 되고 링크 연결 필요 없을 것 같으니까 이 링크 부분 지워주면 될 것 같아요!
지금 이 상태에서 친구 찾기 글씨를 누르면 소린이 페이지로 이동하게 되는거죠...하하
저번에 리뷰할 때 꼼꼼히 봐줬어야 했는데... 제 실수입니다ㅜ 죄송해요.... 다음 리뷰는 더 자세하게 보겠습니다!
머지하고 고쳐도 되고 이거 고치고 머지해도 돼요~!

2021-08-07 15:58 UTC, kiiiyeon commented on src/components/friends/Friends.js
> +          friendsList.map((friend, index) => <p key={index}>{friend}</p>)}
LGTM ㅋㅋ ❤ (소린이 따라하기)

2021-08-07 15:58 UTC, kiiiyeon commented on src/components/friends/UserInfo.js
> -            <h1> 이름: {name} </h1>
하 데박 세심함.... 감동받았음 최고에요 ❤❤❤

2021-08-07 17:28 UTC, lizuAg commented on src/components/friends/Friends.js
> +        친구 찾기
아니에요 !! 제가 좀 더 꼼꼼하게 코드를 살펴봣어야 했는데, 나태했네요 !! h1태그로 수정완료 했습니다 >.<


++. 오류인 것도 있어서 다시 코드리뷰 리퀘 햇습니다 대짱님 감사함다 🥰🥰

2021-08-07 17:30 UTC, kiiiyeon approved these changes
당신은 천재개발자.... 수정 부탁드린거 다 반영해줘서 너무너무 고마와요❤❤❤
늦은시간까지 일하구😭 얼른 자러가세요!!! 넘 고생했습니다 최고최고!!!!

2021-08-08 07:46 UTC, kyungminlee-12 approved these changes
수고하셨습니다!!

2021-08-08 18:12 UTC, bsorinnn approved these changes
와!!! 주은 너무 수고했어요👍👍 코드 정말  깔끔하게 잘 짠 것 같아요! 많이 배워갑니다 ㅎㅎ

2021-08-09 05:41 UTC, KilTae approved these changes
수고하셨어요~~~

2021-08-09 12:50 UTC, merged